# -*- coding: utf-8 -*-
"""Análise de dados com Python e Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asyHWYwIB91Kw7Y_kQMqPrNQmq1fv5xw

# **Análise de dados com Python e Pandas**
"""

#Importando a biblioteca pandas
import pandas as pd

#df = data frame = conjunto de dados igual planilha do excel
#d.read_csv = ler um arquivo csv
df = pd.read_csv("Gapminder.csv",error_bad_lines=False, sep=";") #sep = separador

#Visualizando as 5 primeiras linhas
df.head()

#Troca nome das colunas
df = df.rename(columns={"country":"pais", "continent":"Continente","year":"Anos","lifeExp":"Expectativa de vida","pop":"Pop Total","gdpPercap":"PIB"})

#Exibiri menos linhas
df.head(1) #passe a quantidade dentro do head

#Retorna total de linhas e colunas
df.shape #(linha, coluna)

#Retorna apenas as colunas
df.columns

#Retorna o tipo de dado em cada coluna
df.dtypes #object = string

#Retorna as 5 ultimas linhas
df.tail()

#Retorna as 15 ultimas linhas
df.tail(15)

#Retorna formações estatisticas do conjunto de dados
df.describe()

#Retorna os valores unicos dos continentes sem repetição que temos na noss abase de dados
df["Continente"].unique()

#Mostra as 5 primeiras linhas da Oceania 
Oceania = df.loc[df["Continente"] == "Oceania"]
Oceania.head()

#Guardando em grupos
#Retorna quantos paises tem em cada continente
df.groupby("Continente")["pais"].nunique()

#Mostra qual expectativa de vida media para cada ano
df.groupby("Anos")["Expectativa de vida"].mean()

#traz a media do PIB
df["PIB"].mean()

#Soma do PIB
df["PIB"].sum()

